language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"

env:
  matrix:
    - CONTAO_VERSION=~3.2.0
    - CONTAO_VERSION=~3.3.0
    - CONTAO_VERSION=~3.4.0
    - CONTAO_VERSION=~3.5.0

sudo: false

install:
  - travis_retry composer require contao/core $CONTAO_VERSION --prefer-dist
  - travis_retry composer install --prefer-dist --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647
